[package]
name = "aoc_2016_08"
version = "0.1.0"
authors = ["Georg Begerow <gbegerow+aoc@gmail.com>"]
edition = "2021"

[dependencies]
rstest = { workspace = true }
regex = { workspace = true }
crossterm = { workspace = true, optional = true }
ratatui = { workspace = true, optional = true }

[features]
# default=["viz"]
viz = ["dep:crossterm", "dep:ratatui"]
