[package]
name = "aoc_2016_10"
version = "0.1.0"
authors = ["Georg Begerow <gbegerow+aoc@gmail.com>"]
edition = "2021"

[dependencies]
rstest = { workspace = true }
regex = { workspace = true }
petgraph = { workspace = true, optional = true }

[features]
#default = ["graph"]
graph = ["dep:petgraph"]
