[package]
name = "aoc_2022_18"
version = "0.1.0"
authors = ["Georg Begerow <gbegerow+aoc@gmail.com>"]
edition = "2021"

[dependencies]
# visualize dependencies
bevy = { workspace = true, optional = true }
bevy_panorbit_camera = { workspace = true, optional = true }

[features]
build-visualise = ["bevy", "bevy_panorbit_camera"]

[[bin]]
#cargo run --features build-visualise --bin visualize
name = "visualize"
required-features = ["build-visualise"]
