[package]
name = "aoc_2022_24"
version = "0.1.0"
authors = ["Georg Begerow <gbegerow+aoc@gmail.com>"]
edition = "2021"

[dependencies]
aoc_utils = { path = "../aoc_utils" }
glam = { workspace = true }

[dev-dependencies]
# test-case = "2.2.2"
rstest = { workspace = true }
